CREATE DATABASE SQL_ASSIGNMENT_2;

USE SQL_ASSIGNMENT_2;

--ANS Q1


CREATE TABLE CUSTOMER(
CUSTOMER_ID  INT PRIMARY KEY,
FIRST_NAME	 VARCHAR(50),
LAST_NAME    VARCHAR(50),
EMAIL		 VARCHAR(100),
ADDRESSS	 VARCHAR(100),
CITY		 VARCHAR(50),
STATES		 VARCHAR(50),
ZIP			 NVARCHAR(50));

SELECT * FROM CUSTOMER;

--ANS Q2

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, ADDRESSS, CITY, STATES, ZIP) VALUES
(1, 'GEORGE', 'THOMAS', 'GEORGE.THOMAS@EXAMPLE.COM', '789 OAK ST', 'SAN JOSE', 'CA', 95112),
(2, 'GRACE', 'WILLIAMS', 'TRACE.WILLIAMS@EXAMPLE.COM', '456 MAPLE ST', 'SAN JOSE', 'CA', 95113),
(3, 'TYLER', 'JOHNSON', 'TYLER.JOHNSON@EXAMPLE.COM', '123 ELM ST', 'AUSTIN', 'TX', 78701),
(4, 'GINA', 'BROWN', 'GINA.BROWN@EXAMPLE.COM', '101 PINE AVE', 'MIAMI', 'FL', 33101),
(5, 'TREVOR', 'DAVIS', 'TREVOR.DAVIS@EXAMPLE.COM', '202 BIRCH RD', 'CHICAGO', 'IL', 60601);

SELECT * FROM CUSTOMER;


--ANS Q3

SELECT FIRST_NAME,LAST_NAME FROM CUSTOMER;


--ANS Q4

SELECT * FROM CUSTOMER
WHERE FIRST_NAME LIKE 'G%' AND CITY = 'SAN JOSE';


--ANS Q5

SELECT * FROM CUSTOMER
WHERE Email LIKE '%gmail%';


--ANS Q6
SELECT * FROM CUSTOMER
WHERE last_name NOT LIKE '%A';

