CREATE DATABASE PRACTISE_ASSIGNMENT_3;

USE PRACTISE_ASSIGNMENT_3


--ANS Q1


CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    ORDER_DATE DATE,
    AMOUNT DECIMAL(10, 2),
    CUSTOMER_ID INT
);

--ANS Q2


INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, AMOUNT, CUSTOMER_ID)
VALUES
(101, '2024-08-01', 250.00, 1),
(102, '2024-08-02', 150.50, 2),
(103, '2024-08-03', 320.75, 3),
(104, '2024-08-04', 89.99, 4),
(105, '2024-08-05', 450.00, 5);

SELECT * FROM ORDERS;

/* ANS Q3 CUSTOMER TABLE CREATION */

CREATE TABLE CUSTOMER(
CUSTOMER_ID  INT PRIMARY KEY,
FIRST_NAME	 VARCHAR(50),
LAST_NAME    VARCHAR(50),
EMAIL		 VARCHAR(100),
ADDRESSS	 VARCHAR(100),
CITY		 VARCHAR(50),
STATES		 VARCHAR(50),
ZIP			 NVARCHAR(50));

/* ANS Q3 CUSTOMER TABLE VALUES INSERTION */

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, ADDRESSS, CITY, STATES, ZIP) VALUES
(1, 'GEORGE', 'THOMAS', 'GEORGE.THOMAS@EXAMPLE.COM', '789 OAK ST', 'SAN JOSE', 'CA', 95112),
(2, 'GRACE', 'WILLIAMS', 'TRACE.WILLIAMS@EXAMPLE.COM', '456 MAPLE ST', 'SAN JOSE', 'CA', 95113),
(3, 'TYLER', 'JOHNSON', 'TYLER.JOHNSON@EXAMPLE.COM', '123 ELM ST', 'AUSTIN', 'TX', 78701),
(4, 'GINA', 'BROWN', 'GINA.BROWN@EXAMPLE.COM', '101 PINE AVE', 'MIAMI', 'FL', 33101),
(5, 'TREVOR', 'DAVIS', 'TREVOR.DAVIS@EXAMPLE.COM', '202 BIRCH RD', 'CHICAGO', 'IL', 60601);


SELECT * FROM CUSTOMER;


--ANS Q3

SELECT * FROM CUSTOMER C INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID;


--ANS Q4


SELECT CUSTOMER.CUSTOMER_ID, CUSTOMER.FIRST_NAME,CUSTOMER.LAST_NAME, ORDERS.ORDER_ID, ORDERS.ORDER_DATE, ORDERS.AMOUNT
FROM CUSTOMER
LEFT JOIN ORDERS ON CUSTOMER.CUSTOMER_ID = ORDERS.CUSTOMER_ID;

SELECT CUSTOMER.CUSTOMER_ID, CUSTOMER.FIRST_NAME,CUSTOMER.LAST_NAME, ORDERS.ORDER_ID, ORDERS.ORDER_DATE, ORDERS.AMOUNT
FROM CUSTOMER
RIGHT JOIN ORDERS ON CUSTOMER.CUSTOMER_ID = ORDERS.CUSTOMER_ID;

--ANS Q5


SELECT CUSTOMER.CUSTOMER_ID, CUSTOMER.FIRST_NAME,CUSTOMER.LAST_NAME, ORDERS.ORDER_ID, ORDERS.ORDER_DATE, ORDERS.AMOUNT
FROM CUSTOMER
FULL OUTER JOIN ORDERS ON CUSTOMER.CUSTOMER_ID = ORDERS.CUSTOMER_ID;


--ANS Q6


UPDATE ORDERS
SET AMOUNT = 100
WHERE CUSTOMER_ID = 3;

SELECT * FROM ORDERS;


