CREATE DATABASE PRACTISE_ASSIGNMENT_6;

USE PRACTISE_ASSIGNMENT_6;

CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    ORDER_DATE DATE,
    AMOUNT DECIMAL(10, 2),
    CUSTOMER_ID INT
);

INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, AMOUNT, CUSTOMER_ID)
VALUES
(101, '2024-08-01', 250.00, 1),
(102, '2024-08-02', 150.50, 2),
(103, '2024-08-03', 320.75, 3),
(104, '2024-08-04', 89.99, 4),
(105, '2024-08-05', 450.00, 5);

SELECT * FROM ORDERS;


CREATE TABLE CUSTOMER(
CUSTOMER_ID  INT PRIMARY KEY,
FIRST_NAME	 VARCHAR(50),
LAST_NAME    VARCHAR(50),
EMAIL		 VARCHAR(100),
ADDRESSS	 VARCHAR(100),
CITY		 VARCHAR(50),
STATES		 VARCHAR(50),
ZIP			 NVARCHAR(50));

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, ADDRESSS, CITY, STATES, ZIP) VALUES
(1, 'GEORGE', 'THOMAS', 'GEORGE.THOMAS@EXAMPLE.COM', '789 OAK ST', 'SAN JOSE', 'CA', 95112),
(2, 'GRACE', 'WILLIAMS', 'TRACE.WILLIAMS@EXAMPLE.COM', '456 MAPLE ST', 'SAN JOSE', 'CA', 95113),
(3, 'TYLER', 'JOHNSON', 'TYLER.JOHNSON@EXAMPLE.COM', '123 ELM ST', 'AUSTIN', 'TX', 78701),
(4, 'GINA', 'BROWN', 'GINA.BROWN@EXAMPLE.COM', '101 PINE AVE', 'MIAMI', 'FL', 33101),
(5, 'TREVOR', 'DAVIS', 'TREVOR.DAVIS@EXAMPLE.COM', '202 BIRCH RD', 'CHICAGO', 'IL', 60601);


SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, ADDRESSS, CITY, STATES, ZIP) VALUES
(6, 'ALINA','JORDAN','ALINAJORDAN@EXAMPLE.COM','311 PEEPAL TREE RD', 'NEW YORK','NY', 45119),
(7, 'MONA','JORDAN','MONAJORDAN@EXAMPLE.COM','447 BUNION HOSPITAL RD', 'NEW YORK','NY',45129);


UPDATE CUSTOMER
SET LAST_NAME = 'SMITH'
WHERE FIRST_NAME = 'MONA';


SELECT * FROM CUSTOMER;


--ANS Q1

CREATE VIEW CUSTOMER_SAN_JOSE
AS SELECT * FROM CUSTOMER
WHERE CITY='SAN JOSE';

SELECT * FROM CUSTOMER_SAN_JOSE;

--ANS Q2

BEGIN TRANSACTION
UPDATE CUSTOMER
SET FIRST_NAME = 'FRANCIS'
WHERE LAST_NAME = 'JORDAN';

SELECT * FROM CUSTOMER;

ROLLBACK

SELECT * FROM CUSTOMER;

BEGIN TRANSACTION
UPDATE CUSTOMER
SET FIRST_NAME = 'ALEX'
WHERE LAST_NAME = 'JORDAN';

SELECT * FROM CUSTOMER;

COMMIT

--ANS Q3

BEGIN TRY

	DECLARE @RESULT INT
	SET @RESULT = 100/0

END TRY

	BEGIN CATCH 
	PRINT ERROR_MESSAGE()

END CATCH

--ANS Q4

BEGIN TRANSACTION;

	INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, AMOUNT, CUSTOMER_ID)
	VALUES (106, '2024-11-25', 800.00, 6);

	SELECT * FROM ORDERS;

COMMIT;


