CREATE DATABASE PRACTISE_ASSIGNMENT_5;

USE PRACTISE_ASSIGNMENT_5;

CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    ORDER_DATE DATE,
    AMOUNT DECIMAL(10, 2),
    CUSTOMER_ID INT
);

INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, AMOUNT, CUSTOMER_ID)
VALUES
(101, '2024-08-01', 250.00, 1),
(102, '2024-08-02', 150.50, 2),
(103, '2024-08-03', 320.75, 3),
(104, '2024-08-04', 89.99, 4),
(105, '2024-08-05', 450.00, 5);

SELECT * FROM ORDERS;

--ANS Q1

SELECT *FROM ORDERS
ORDER BY AMOUNT DESC;

--ANS Q2

CREATE TABLE EMPLOYEE_DETALIS_1(
EMP_ID  INT PRIMARY KEY,
EMP_NAME   VARCHAR(50),
EMP_SALARY MONEY
);

CREATE TABLE EMPLOYEE_DETALIS_2(
EMP_ID  INT PRIMARY KEY,
EMP_NAME   VARCHAR(50),
EMP_SALARY MONEY
);

INSERT INTO EMPLOYEE_DETALIS_1 VALUES
(1,'GEORGE',999.00),
(2,'TYLER',850.66),
(3,'RINKU',739.05);

INSERT INTO EMPLOYEE_DETALIS_2 VALUES
(4,'TOM',1036.00),
(5,'EMILY',550.46),
(6,'CATHERINE',1233.11);

SELECT * FROM EMPLOYEE_DETALIS_1;
SELECT * FROM EMPLOYEE_DETALIS_2;



--ANS Q3

SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETALIS_1
UNION
SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETALIS_2;


--ANS Q4

SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETALIS_1
INTERSECT
SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETALIS_2;


--ANS Q5

/*  SENARIO-1 */

SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETALIS_1
EXCEPT
SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETALIS_2;

/* SENARIO-2 */

SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETALIS_2
EXCEPT
SELECT EMP_ID,EMP_NAME,EMP_SALARY FROM EMPLOYEE_DETALIS_1;